
export enum ActionsTypes {
  ADD_PATH= 'ADD_PATH',
  REMOVE_PATH = 'REMOVE_PATH',
  ROOT_PATH= 'ROOT_PATH',
  SHOW_FOLDERS = 'SHOW_FOLDERS',
  ADD_REMOVE_FOLDER = 'ADD_REMOVE_FOLDER',
  DELETE_REMOVE_FOLDER = 'DELETE_REMOVE_FOLDER',
  REMOVE_FOLDERS = 'REMOVE_FOLDERS',
  SHOW_VIDEO = 'SHOW_VIDEO',
  SHOW_PDF = 'SHOW_PDF',
  SHOW_PHOTO = 'SHOW_PHOTO',
  SHOW_TXT = 'SHOW_TXT'
}
